# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Fiducial_Estimator <- function(l, r, timepoints, tau, alpha) {
    .Call('_FICE_Fiducial_Estimator', PACKAGE = 'FICE', l, r, timepoints, tau, alpha)
}

